### ISSUE TITLE
Flickering, wrong show/hide of errors on multiple clicks of submit

### ISSUE THREAD

**Issue by scharfmn** [Thrilleratplay/jquery-validation-bootstrap-tooltip#9] opened 2015-03-23 10:06 UTC
When I leave all required fields, or some required fields, blank on my form, and push submit repeatedly (without changing the form in any way), I get the following:

first click the tooltips appear 
second click, the tooltips disappear
third click, the tooltips appear
etc.

I also get tooltip flickering if have an incorrectly filled-in field along with the blank required ones.

And it's possible to get errors out of sync with one another by filling in a field, hitting submit, then making it blank: its tooltip will turn on and off with multiple submits, but out of phase with the other, non-previously-filled-in blank requied fields.

Is there a setting I'm missing? 

I'll try to construct a fiddle if it will help, but maybe you've seen this before.

**Comment by Thrilleratplay** [comment] 2015-03-23 13:09
For your inputs, are you specifying "required" as a class or attribute? Using the required attribute will, or should, leave the tooltips visible even on blur. 

As far as flickering is concerned, someone mentioned this issue a week or so ago and it seemed to be due to the version of jQuery Validation shipped with ASP MVC.  If you are using this, take a look at [ jQuery Validation Unobtrusive  Native](http://johnnyreilly.github.io/jQuery.Validation.Unobtrusive.Native/index.html) and in particular [advantage #2's demo](http://johnnyreilly.github.io/jQuery.Validation.Unobtrusive.Native/AdvancedDemo/Tooltip.html).

**Comment by Thrilleratplay** [comment] 2015-03-30 04:08
Closing pending more information.

**Comment by demelvin** [comment] 2015-03-31 16:54
Hey guys. I am also seeing this same behavior. I tried adding the required attribute and required class but this had no effect on the outcome. I will take a look at the code if I have time and see if I can't figure out what the deal is.

I am not using JQuery Validation shipped with ASP MVC.

**Comment by Thrilleratplay** [comment] 2015-04-01 02:05
Hmmm.  I wonder why different developers are having this issue all of a sudden?  

@demelvin can you provide the versions of Bootstrap, jQuery and jQuery Validation used as well as browser information?

**Comment by demelvin** [comment] 2015-04-01 02:11
@Thrilleratplay absolutely

Bootstrap - v3.3.2
JQuery - v2.0.3
JQuery Validation - v0.6

I am working on something else at the moment so I haven't had time to look into this. Please let me know if you need anything else.

**Comment by Thrilleratplay** [comment] 2015-04-03 04:28
@scharfmn @demelvin I may have an update on this.  

I created a fiddle and was able to reproduce the flickering problem.  I did some testing by swapping in and out different versions of jQuery, jQuery Validation and Bootstrap and found that the problem seems to come from Bootstrap v3.3.0 or later.  I tried to find what changed that would have caused this however I did not see anything.  If possible, my suggestion would be to downgrade to Bootstrap 3.2 and see if that solves the problem.

**Comment by Thrilleratplay** [comment] 2015-05-05 12:19
@scharfmn @demelvin As much as I wanted to avoid doing so for simplicity sake, I added the flickerfix version into this repo to deal with the problems created by Bootstrap 3.3.0+.

**Closed by Thrilleratplay** 2015-05-05 12:19 UTC

**Comment by demelvin** [comment] 2015-05-05 14:42
@Thrilleratplay awesome! I'll pull it down and check it out later today. Thank you.

**Comment by scharfmn** [comment] 2015-05-10 08:12
@Thrilleratplay Thank you very much. Was using this at work, and we had to move on, but I will be returning. Best wishes, & thanks again.

**Comment by demelvin** [comment] 2015-06-09 03:35
@Thrilleratplay finally got around to adding this to my application. Works great! Thanks for the awesome code.
